name: Python CI

on:
  pull_request:
  push:
    branches:
      - main
      - "release/**"

jobs:
  # syntaxのチェック
  syntax_check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: pip install tox

    - name: Lint with flake8
      run: tox -e flake8

    - name: Lint with mypy
      run: tox -e mypy

  # UnitTest
  unit_tests:
    runs-on: ubuntu-latest
    needs: syntax_check

    strategy:
      fail-fast: false
      matrix:
        version: [
          {python: 3.7, tox: py37},
          {python: 3.8, tox: py38},
          {python: 3.9, tox: py39}
        ]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.version.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.version.python }}

    - name: Install dependencies
      run: pip install tox

    - name: Test with pytest
      run: tox -e ${{ matrix.version.tox }}
